# 배열 구현과 연결 구현 비교

같은 이진트리를 배열과 포인터로 각각 만들어 놓고, 메모리를 얼마나 쓰는지와 노드 관계를 찾는 데 얼마나 걸리는지 비교했습니다.

## [1] 메모리 사용량 비교

트리는 노드 수를 7개, 15개, 20개로 맞춰서 세 종류를 만들었습니다.

- **일반**: 루트에서 랜덤하게 왼쪽/오른쪽으로 내려가다가 빈자리에 노드를 넣음
- **완전**: 1번부터 n번까지 순서대로 채움
- **편향**: 오른쪽 자식으로만 쭉 이어짐

n = 7일 때 실제로 쓴 트리입니다.

```
일반 : A(B(D,E(,K)),C(,G))
완전 : A(B(D,E),C(F,G))
편향 : A(,C(,G(,O(,E(,K(,W))))))
```

### 측정 결과

| 종류 | n | 높이 h | 배열 칸 수 | 배열(byte) | 연결(byte) | 칸 사용률 |
|---|--:|--:|--:|--:|--:|--:|
| 일반 | 7 | 4 | 16 | 16 | 168 | 46.7% |
| 완전 | 7 | 3 | 8 | 8 | 168 | 100% |
| 편향 | 7 | 7 | 128 | 128 | 168 | 5.5% |
| 일반 | 15 | 5 | 32 | 32 | 360 | 48.4% |
| 완전 | 15 | 4 | 16 | 16 | 360 | 100% |
| 편향 | 15 | 15 | 32,768 | 32,768 | 360 | 0.046% |
| 일반 | 20 | 7 | 128 | 128 | 480 | 15.7% |
| 완전 | 20 | 5 | 32 | 32 | 480 | 64.5% |
| 편향 | 20 | 20 | 1,048,576 | 1,048,576 | 480 | 0.002% |

칸 사용률은 `n / (배열 칸 수 - 1)`입니다. 0번 칸은 안 쓰니까 빼고 계산했습니다.

### 결과 분석

표를 보면 두 구현의 사용량은 이렇게 정리됩니다.

```
배열 = 2^h x s          -> 높이(h)로 결정됨
연결 = n x (s + 2p)     -> 노드 수(n)로 결정됨
```

(s = 데이터 크기, p = 포인터 크기)

**완전 이진트리**는 배열이 압도적으로 좋습니다. n = 15일 때 배열은 16바이트인데 연결은 360바이트로 **22.5배 차이**가 납니다.

**일반 이진트리**는 중간중간 빈칸이 생겨서 사용률이 떨어집니다. 그래도 높이가 노드 수에 비해 크지 않아서(n = 20일 때 h = 7) 배열 128바이트, 연결 480바이트로 배열이 더 적게 씁니다.

**편향 이진트리**에서 확 갈립니다. 노드 수랑 높이가 같아져서(h = n) 배열 크기가 2^n으로 커집니다. n이 7 -> 15 -> 20으로 갈 때 배열은 128 -> 32,768 -> 1,048,576바이트로 폭발하는데, 연결은 168 -> 360 -> 480바이트로 그냥 일정하게 늘어납니다.

---

## [2] 자식, 부모, 형제 노드 찾기

### 프로그램

노드 이름을 입력받아서 두 구현에서 각각 부모/자식/형제를 출력합니다.
과정을 **① 이름으로 노드 찾기**와 **② 찾은 다음 관계 계산하기** 두 단계로 나눠서 비용을 따로 셌습니다.

**배열 구현**

```c
void arr_query(const ArrayTree *t, char key)
{
    size_t steps = 0, found = 0;
    for (size_t i = 1; i < t->cap; i++) {
        steps++;
        if (t->data[i] == key) { found = i; break; }
    }
    if (!found) { printf("없음\n"); return; }

    size_t parent  = found / 2;
    size_t left    = 2 * found;
    size_t right   = 2 * found + 1;
    size_t sibling = found > 1 ? (found ^ 1) : 0;
}
```

**연결 구현**

```c
void lnk_query(Node *root, char key)
{
    Node *x = lnk_find(root, key, &find_steps);
    if (!x) { printf("없음\n"); return; }

    Node *left  = x->left;
    Node *right = x->right;
    Node *p = (x == root) ? NULL
                          : lnk_parent(root, x, &parent_steps);
    Node *s = p ? (p->left == x ? p->right : p->left) : NULL;
}
```

노드에 부모 포인터가 없으니까 부모를 찾으려면 루트부터 다시 훑어야 합니다.

### 시간 복잡도

| 연산 | 배열 | 연결 |
|---|:---:|:---:|
| 이름으로 노드 찾기 | O(2^h) (빈칸까지 검사) | O(n) |
| 자식 찾기 | O(1) | O(1) |
| 부모 찾기 | O(1) | O(n) |
| 형제 찾기 | O(1) | O(n) (부모부터 찾아야 함) |

### 실제로 돌려본 결과

| 트리 | 찾은 노드 | 배열: 검사한 칸 | 배열: 관계 계산 | 연결: 방문 노드 | 연결: 부모 찾기 |
|---|:---:|--:|:---:|--:|--:|
| `A(B(D,E),C(,F))` | E | 5 | O(1) | 4 | 2 |
| `A(B(D,E),C(,F))` | F | 7 | O(1) | 6 | 5 |
| 포화 트리 15개 | J | 10 | O(1) | 7 | 6 |
| 편향 트리 10개 | J (마지막) | **1,023** | O(1) | 10 | 9 |
| 아무 트리나 | A (루트) | 1 | O(1) | 1 | 0 |

포화 트리: `A(B(D(H,I),E(J,K)),C(F(L,M),G(N,O)))`
편향 트리: `A(,B(,C(,D(,E(,F(,G(,H(,I(,J)))))))))`

### 어느 쪽이 더 효율적인지

**관계를 계산하는 것만 보면 배열이 훨씬 효율적입니다.** 인덱스만 알면 부모는 `i/2`, 자식은 `2i`, `2i+1`, 형제는 `i^1`로 끝나서 트리가 아무리 커져도 O(1)입니다. 연결 구현은 자식만 O(1)이고, 부모 포인터가 없어서 부모랑 형제를 구하려면 루트부터 다시 순회해야 합니다. 포화 트리에서 J를 찾을 때 연결 구현은 찾는 데 7개, 부모 찾는 데 6개 해서 총 13번 노드를 방문했습니다.

**근데 노드를 찾는 것까지 합치면 트리 모양에 따라 달라집니다.** 배열은 빈칸까지 전부 검사해야 해서, 비용이 노드 수가 아니라 배열 크기(2^h)에 비례합니다. 완전/포화 트리에서는 빈칸이 없어서 비슷한데(10칸 vs 13번 방문), 10개짜리 편향 트리에서 마지막 노드를 찾을 때는 배열이 **1,023칸**을 뒤진 반면 연결은 19번(10 + 9)만 방문했습니다.

**정리하면,**

- 완전 이진트리에 가깝거나, 이미 인덱스를 알고 위아래로 오르내리는 경우는 **배열이 유리**합니다.
- 편향되거나 모양이 들쭉날쭉한 트리는 탐색이나 메모리나 **연결이 안정적**입니다.
- 부모를 자주 찾아야 한다면 노드에 `parent` 포인터를 추가하면 부모/형제도 O(1)로 만들 수 있습니다.
